### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by connellybarnes** [chengyangfu/pytorch-vgg-cifar10#1]
Hi Cheng-Yang,

Thanks for the CIFAR10 training code.

I wonder whether you would be interested to please license this code under an open source license? See e.g. the licenses here:

https://opensource.org/licenses

If so, then others will be more likely to contribute to your codebase, or incorporate it into their projects.

**Comment by chengyangfu** [comment]
Thanks for the suggestion!  
Feel free to modify this.
