### ISSUE TITLE
Question regarding VGG cfg

### ISSUE THREAD

**Issue by isalirezag** [chengyangfu/pytorch-vgg-cifar10#4]
Sorry I have a stupid question.
in the cfg: [64, 'M', 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512, 'M'],

what 'M' stands for?

**Comment by chengyangfu** [comment]
Hi @isalirezag , 
   'M' means max pooling here. 
   Please check these [lines.](https://github.com/chengyangfu/pytorch-vgg-cifar10/blob/master/vgg.py#L50-L51).
