### ISSUE TITLE
which pytorch version did you use to train this model? i am trying to do torch. load on my CPU but even after i give map_location cpu, it still gives pytorch not compiled for CUDA enabled assertion error

### ISSUE THREAD

**Issue by Adnan-annan** [chengyangfu/pytorch-vgg-cifar10#6]

**Comment by chengyangfu** [comment]
Hi @Adnan-annan, 
       Which PyTorch version you are using now?
       This code was implemented 1~2 years ago. I cannot remember all the details. It should be PyTorch 0.3 or 0.4. Due to the dramatical updates in PyTorch 1.0.0, there is a high chance you may need to modify some parts to make it work.

**Comment by chengyangfu** [comment]
updated the code. It works with my PyTorch 1.0.0. now. Let me know if it still causes any problem.

**Comment by chengyangfu** [comment]
Okay. The problem is caused because there is no gpu in your environment. 
If you have the GPU in the machine, make sure setting the `CUDA_VISIBLE_DEVICE` properly before running the code. 
I add the support to run the code in CPU mode. You can add ```--cpu``` and see the instructions in README. But Keep in mind, cpus are not efficient for training.

**Comment by Adnan-annan** [comment]
Thanks for your reply, i want to use the trained model and use it for my own research, i am using cpu at the moment, so i would like to just run the trained model in my cpu first and later i will fine tune it for my own purpose. but it not loading your trained model on my cpu, may be the problem is pytorch version mismatch.

**Comment by Adnan-annan** [comment]
unfortunately wget http://www.cs.unc.edu/~cyfu/cifar10/model_bes_cpu.pth.tar is not working,,, it gives ERROR 404: Not Found. error :(

**Comment by Adnan-annan** [comment]
oh it should be wget http://www.cs.unc.edu/~cyfu/cifar10/model_best_cpu.pth.tar . It works now
