### ISSUE TITLE
Is your code based on a code template?

### ISSUE THREAD

**Issue by Anonymous-so** [chengyangfu/pytorch-vgg-cifar10#8]
I once saw a code on AlexNet that is very similar to your coding style（https://github.com/jiecaoyu/pytorch_imagenet）...
May I ask that is your code based on a standard code template?

**Comment by chengyangfu** [comment]
The code was based on the PyTorch ImageNet example. However, the code was implemented three years ago, so a lot of things might change now.

**Comment by Anonymous-so** [comment]
Oh I see~thank you^ ^
